@api = http://localhost:3000/api

### POST /auth/signin (login a user)
POST {{api}}/auth/signin
Content-Type: application/json

{
  "email": "user2.1@ucol.mx",
  "password": "20185355H"
}

//**************************************************************

### POST /autha/signup (register a new campo)

POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "user3",
  "email": "user3@ucol.mx",
  "password": "20185355H",
  "roles": ["user"]
}

