@api = http://localhost:3000/api

### POST /users (create a new user)
POST {{api}}/users
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYzZlNDNhZmJkYWI4MGVmMTgxZWQzNiIsImlhdCI6MTYyNDA0NjI4NSwiZXhwIjoxNjI0MzA1NDg1fQ.FAd2MTZsueFb3LcPaSZfHOyhzL4a1zgUPl1Qmfsf0VE

{
  "username": "Admin3",
  "email": "Admin3@ucol.mx",
  "password": "20185355H",
  "roles": ["admin"]
}


### GET /USERS (get all users)
GET {{api}}/users
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYzZlNDRhZmJkYWI4MGVmMTgxZWQzNyIsImlhdCI6MTYyNDA0NjMxOSwiZXhwIjoxNjI0MzA1NTE5fQ.yVS9XQz8ml4yEfG_96R-V4_Ql9jF0YdQ0RzQ_0AbbFU

### GET /users/:userID
GET {{api}}/users/60c6e44afbdab80ef181ed37
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYzZlNDNhZmJkYWI4MGVmMTgxZWQzNiIsImlhdCI6MTYyNDA0NjI4NSwiZXhwIjoxNjI0MzA1NDg1fQ.FAd2MTZsueFb3LcPaSZfHOyhzL4a1zgUPl1Qmfsf0VE

### PUT /user/:userId
PUT {{api}}/users/60cd01e014abd3285c9b9ff9
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYzc2N2Y1NzBlYjQzMjliMTc0NzlkNSIsImlhdCI6MTYyNDA0NjI0MSwiZXhwIjoxNjI0MzA1NDQxfQ.BUAqUOGPTEfi03YFpzYqVksaaggJoMFDv0IA8eCKLyM

{
  "email": "user2.2@ucol.mx",
  "roles": ["user"]
}

### DEL /users/:userId
DELETE {{api}}/users/60cd01e014abd3285c9b9ff9
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYzc2N2Y1NzBlYjQzMjliMTc0NzlkNSIsImlhdCI6MTYyNDA0NjI0MSwiZXhwIjoxNjI0MzA1NDQxfQ.BUAqUOGPTEfi03YFpzYqVksaaggJoMFDv0IA8eCKLyM


//**************************************************************